Global:
  device: gpu
  epoch_num: 80
  log_smooth_window: 20
  print_batch_step: 10
  output_dir: ./output/rec/ablation_msr/svtrv2_smtr_gtc_rctc
  save_epoch_step: 
  - 0
  - 1 
  eval_batch_step:
  - 0
  - 500
  eval_epoch_step:
  - 0
  - 1
  cal_metric_during_train: true
  pretrained_model: ./output/rec/ablation_msr/svtrv2_smtr_gtc_rctc/best.pth
  checkpoints: null
  use_tensorboard: false
  infer_img: C:/Users/anhhu/MultiFrame-LPR/data/openocr_infer_list.txt
  character_dict_path: ./tools/utils/EN_lp_symbol_dict.txt
  max_text_length: 25
  use_space_char: false
  save_res_path: C:/Users/anhhu/MultiFrame-LPR/data/openocr_results.txt
  use_amp: true
  distributed: true
Optimizer:
  name: AdamW
  lr: 0.00002
  weight_decay: 0.05
  filter_bias_and_bn: true
LRScheduler:
  name: OneCycleLR
  warmup_epoch: 1.5
  cycle_momentum: false
Architecture:
  model_type: rec
  algorithm: SVTRv2
  in_channels: 3
  Transform: null
  Encoder:
    name: SVTRv2LNConvTwo33
    use_pos_embed: false
    dims:
    - 128
    - 256
    - 384
    depths:
    - 6
    - 6
    - 6
    num_heads:
    - 4
    - 8
    - 12
    mixer:
    - - Conv
      - Conv
      - Conv
      - Conv
      - Conv
      - Conv
    - - Conv
      - Conv
      - FGlobal
      - Global
      - Global
      - Global
    - - Global
      - Global
      - Global
      - Global
      - Global
      - Global
    local_k:
    - - 5
      - 5
    - - 5
      - 5
    - - -1
      - -1
    sub_k:
    - - 1
      - 1
    - - 2
      - 1
    - - -1
      - -1
    last_stage: false
    feat2d: true
  Decoder:
    name: GTCDecoder
    infer_gtc: true
    detach: false
    gtc_decoder:
      name: SMTRDecoder
      num_layer: 1
      ds: true
      max_len: 25
      next_mode: true
      sub_str_len: 5
    ctc_decoder:
      name: RCTCDecoder
Loss:
  name: GTCLoss
  ctc_weight: 0.1
  gtc_loss:
    name: SMTRLoss
PostProcess:
  name: GTCLabelDecode
  gtc_label_decode:
    name: SMTRLabelDecode
    next_mode: true
  character_dict_path: ./tools/utils/EN_lp_symbol_dict.txt
  use_space_char: false
Metric:
  name: RecGTCMetric
  main_indicator: acc
  is_filter: true
Train:
  dataset:
    name: RatioDataSetTVResize
    ds_width: true
    padding: false
    data_dir_list:
    - /workspace/lp_for_openocr/lmdb
    transforms:
    - DecodeImagePIL:
        img_mode: RGB
    - PARSeqAugPIL: null
    - GTCLabelEncode:
        gtc_label_encode:
          name: SMTRLabelEncode
          sub_str_len: 5
        character_dict_path: ./tools/utils/EN_lp_symbol_dict.txt
        use_space_char: false
        max_text_length: 25
    - KeepKeys:
        keep_keys:
        - image
        - label
        - label_subs
        - label_next
        - length_subs
        - label_subs_pre
        - label_next_pre
        - length_subs_pre
        - length
        - ctc_label
        - ctc_length
  sampler:
    name: RatioSampler
    scales:
    - - 128
      - 32
    first_bs: 128
    fix_bs: false
    divided_factor:
    - 4
    - 16
    is_training: true
  loader:
    shuffle: true
    batch_size_per_card: 128
    drop_last: true
    max_ratio: 12
    num_workers: 0
Eval:
  dataset:
    name: RatioDataSetTVResize
    ds_width: true
    padding: false
    data_dir_list:
    - /workspace/lp_for_openocr/lmdb
    transforms:
    - DecodeImagePIL:
        img_mode: RGB
    - GTCLabelEncode:
        gtc_label_encode:
          name: SMTRLabelEncode
        character_dict_path: ./tools/utils/EN_lp_symbol_dict.txt
        use_space_char: false
        max_text_length: 25
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
        - ctc_label
        - ctc_length
  sampler:
    name: RatioSampler
    scales:
    - - 128
      - 32
    first_bs: 128
    fix_bs: false
    divided_factor:
    - 4
    - 16
    is_training: false
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 128
    max_ratio: 12
    num_workers: 0